version: '2'

volumes:
  postgresql-data:
  pgadmin-data:

services:
    redis:
        hostname: redis
        container_name: redis
        image: ${IMAGE_NAME_REDIS}:${IMAGE_NAME_REDIS_TAG}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - 6379:6379
        volumes:
            - ./data/redis:/data
        environment:
            - REDIS_PORT=6379

    redis-insights:
        hostname: redis-insights
        container_name: redis-insights
        image: ${IMAGE_NAME_REDISINSIGHT}:${IMAGE_NAME_REDISINSIGHT_TAG}
        ports:
            - 8001:8001
        volumes:
            - ./data/redisinsight:/db

    postgres:
        hostname: postgres
        container_name: postgres
        image: ${IMAGE_NAME_POSTGRES}:${IMAGE_NAME_POSTGRES_TAG}
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow

    pgadmin:
        hostname: pgadmin
        container_name: pgadmin
        image: ${IMAGE_NAME_PGADMIN}:${IMAGE_NAME_PGADMIN_TAG}
        ports:
            - 5050:80
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=airflow@airflow.com
            - PGADMIN_DEFAULT_PASSWORD=airflow

    airflow-webserver:
        hostname: airflow-webserver
        container_name: airflow-webserver
        command: webserver
        image: ${IMAGE_NAME_AIRFOW}:${IMAGE_NAME_AIRFOW_TAG}
        volumes:
            # - ./dags:/opt/airflow/dags
            - ./packages:/opt/airflow/packages
            - ./logs:/opt/airflow/logs
        user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
        depends_on:
            - redis
            - postgres
            - airflow-init
        ports:
            - 8080:8080
        environment:
            AIRFLOW__CORE__EXECUTOR: CeleryExecutor
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
            AIRFLOW__CORE__FERNET_KEY: ''
            AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
            AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
            AIRFLOW__WEBSERVER__WORKERS: 1
            AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'False'
            AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 10

    airflow-scheduler:
        hostname: airflow-scheduler
        container_name: airflow-scheduler
        command: scheduler
        image: ${IMAGE_NAME_AIRFOW}:${IMAGE_NAME_AIRFOW_TAG}
        volumes:
            - ./dags:/opt/airflow/dags
            - ./packages:/opt/airflow/packages
            - ./logs:/opt/airflow/logs
        user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
        depends_on:
            - redis
            - postgres
        environment:
            AIRFLOW__CORE__EXECUTOR: CeleryExecutor
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
            AIRFLOW__CORE__FERNET_KEY: ''
            AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
            AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
            AIRFLOW__WEBSERVER__WORKERS: 1
            AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'False'
            AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 10

    airflow-worker:
        hostname: airflow-worker
        container_name: airflow-worker
        # deploy:
        #   replicas: 1
        command: celery worker
        image: ${IMAGE_NAME_AIRFOW}:${IMAGE_NAME_AIRFOW_TAG}
        volumes:
            - ./dags:/opt/airflow/dags
            - ./packages:/opt/airflow/packages
            - ./logs:/opt/airflow/logs
        user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
        depends_on:
            - redis
            - postgres
        environment:
            AIRFLOW__CORE__EXECUTOR: CeleryExecutor
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
            AIRFLOW__CORE__FERNET_KEY: ''
            AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
            AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
            AIRFLOW__WEBSERVER__WORKERS: 1
            AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'False'
            AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 10

    airflow-init:
        hostname: airflow-init
        container_name: airflow-init
        command: version
        image: ${IMAGE_NAME_AIRFOW}:${IMAGE_NAME_AIRFOW_TAG}
        volumes:
            - ./logs:/opt/airflow/logs
        user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
        depends_on:
            - redis
            - postgres
        environment:
            _AIRFLOW_DB_UPGRADE: 'True'
            _AIRFLOW_WWW_USER_CREATE: 'True'
            _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
            _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
            AIRFLOW__CORE__EXECUTOR: CeleryExecutor
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
            AIRFLOW__CORE__FERNET_KEY: ''
            AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
            AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
            AIRFLOW__WEBSERVER__WORKERS: 1
            AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'False'
            AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 10

    flower:
        hostname: flower
        container_name: flower
        command: celery flower
        image: ${IMAGE_NAME_AIRFOW}:${IMAGE_NAME_AIRFOW_TAG}
        volumes:
            - ./logs:/opt/airflow/logs
        user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
        depends_on:
            - redis
            - postgres
        ports:
            - 5555:5555
        environment:
            AIRFLOW__CORE__EXECUTOR: CeleryExecutor
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
            AIRFLOW__CELERY__BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
            AIRFLOW__CORE__FERNET_KEY: ''
            AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
            AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
            AIRFLOW__WEBSERVER__WORKERS: 1
            AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
            AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'False'
            AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 10
